// export const SET_NAVLINK = "SET_NAVLINK";
// export const SET_SUB_NAVLINK = "SET_SUB_NAVLINK";
export const SET_USER_DATA = "SET_USER_DATA";
export const SET_CREATEJOB_JOBFIELDS = "SET_CREATEJOB_JOBFIELDS";
export const SET_CREATEJOB_MILESTONEFIELDS = "SET_CREATEMILESTONE_MILESTONEFIELDS";
export const CANCEL_CREATEJOB = "CANCEL_CREATEJOB";
export const SET_CREATEJOB_JOBVALIDATION = "SET_CREATEJOB_JOBVALIDATION";
export const SET_CREATEJOB_MILESTONEVALIDATION = "SET_CREATEJOB_MILESTONEVALIDATION";